### ISSUE TITLE
AttributeError: Enum AudioEncoding has no value defined for name 'OGGOPUS'

### ISSUE THREAD

**Issue by ai-nikolai** [nvidia-riva/python-clients#36]
`nvidia-riva-client==2.8.0`

When calling:
```
import riva.client
riva.client.AudioEncoding.OGGOPUS
```

We get the following error:
`AttributeError: Enum AudioEncoding has no value defined for name 'OGGOPUS'`

However, your latest `.proto` files in `common` have this option available: https://github.com/nvidia-riva/common/blob/main/riva/proto/riva_audio.proto

Please clarify which options are available for which models and api and client versions, etc. Thank you.

**Comment by virajkarandikar** [comment]
Closing this. Please reopen if required.

**Comment by ai-nikolai** [comment]
@PeganovAnton thanks a lot for the reply. I must have missed the previous notification as well, sorry about that. 

Thanks for the swift fix.
