### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by rawathemant246** [nvidia-riva/python-clients#46]
cannot import name 'cygrpc' from 'grpc._cython' ([d:\Anaconda\envs\Nvidia_riva\lib\site-packages\grpc\_cython\__init__.py](file:///D:/Anaconda/envs/Nvidia_riva/lib/site-packages/grpc/_cython/__init__.py))
Output is truncated

Also in the installation procedure 
python3 setup.py bdist_wheel 
File "D:\Deep Learning Projects\Nvidia_riva\python-clients\setup.py", line 12, in <module>
    import grpc_tools.protoc
ModuleNotFoundError: No module named 'grpc_tools'     

pip install --force-reinstall dist/*.whl

WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename

Can you provide me the solution for that. Thanks

**Comment by virajkarandikar** [comment]
Can you install depdendencies? In this case `grpc_tools` is missing.
Try installing it using `python3 -m pip install --user grpcio-tools`

**Comment by virajkarandikar** [comment]
Closing the issue due to inactivity. Please reopen if needed.
